### ISSUE TITLE
Update README.md File for better visualization

### ISSUE THREAD

**Issue by malivinayak** [vivekutture/Currency-Converter#1]
You can put commands in code block as mentioned below

*  Step 1 : Install tkinter : 

```
pip install tkinter / pip install tk
```

* Step 2 :  Install request 
```
pip install requests
```

* Note : 
**`NTERNET connectivity is required` because this is "REAL TIME" Currency Converter.**

**Comment by malivinayak** [comment]
Due to this format anyone can easily copy paste the commands just by one click

**Comment by vivekutture** [comment]
Okay I'll that...
Thank You so much for suggestion

**Comment by vivekutture** [comment]
> Due to this format anyone can easily copy paste the commands just by one click

Okay I'll do that...
Thank You so much for suggestion

**Comment by malivinayak** [comment]
Take a look on the PR #2

**Comment by malivinayak** [comment]
Resolve at #2
